### ISSUE TITLE
pocketchip 可以使用这些软件吗？

### ISSUE THREAD

**Issue by xue-fei** [HandsomeYingyan/mainline-a13-q8#1]
pocketchip 使用的是R8，可以使用这些软件吗？

**Comment by HandsomeYingyan** [comment]
pocketchip原厂系统用的是4.4的内核，并不是主线，所以这个仓库里的东西原厂系统是用不了的。但是如果你搞定了主线内核应该是没有问题的。

**Comment by xue-fei** [comment]
多谢，我可能得得学一下怎么从主线构建pocketchip的系统，这个看起来蛮复杂的，这东西也不能插内存卡，也不知道怎么从USB口启动……
